export const messageError = {
    CPF_INVALIDO: "Erro: padrão de CPF invalido",
    NOME_INVALIDO: "Erro: Nome invalido",
    DATA_NASCIMENTO_INVALIDA: "Erro: Data de Nascimento invalida",
    PACIENTE_MENOR_13_ANOS: "Erro: paciente deve ter pelo menos 13 anos",
    PACIENTE_JA_CADASTRADO: "Erro: CPF já cadastrado",
    ERRO_ATUALIZAR_CONSULTORIO: "Erro: atualizar arquivo de consultorio.json",
    ERRO_BUSCAR_CONSULTORIO: "Erro: buscar consultorio de arquivo consultorio.json",
    PACIENTE_NAO_CADASTRADO: "Erro: paciente não cadastrado",
    DATA_CONSULTA_INVALIDA: "Erro: Data da consulta invalida",
    HORARIO_INDALIDO: "Erro: Horario da consulta invalida",
    HORARIO_CONSULTA_INDISPONIVEL: "Erro: já existe uma consulta agendada nesse horário",
    PACIENTE_JA_POSSUI_CONSULTA_FUTURA: "Erro: Paciente só pode realizar um agendamento futuro por vez.",
    CONSULTA_NAO_ENCONTRADA: "Erro: agendamento não encontrado",
    PACIENTE_AGENDADO: "Erro: paciente está agendado.",
    APRESENTACAO_AGENDA_INVALIDO: "Erro: tipo de apresentacao da agenda só pode ser 'T' ou 'P'",
    BANCO_DE_DADOS_ERRO_CONSULTA: "Erro: ocorreu um erro ao tentarmos uma consulta no banco de dados, tente novamente mais tarde",
    BANCO_DE_DADOS_ERRO_CRIACAO_PACIENTE: "Erro: ocorreu um erro ao tentarmos cadastrar o paciente no banco de dados, tente novamente mais tarde",
    BANCO_DE_DADOS_ERRO_EXCLUSAO_PACIENTE: "Erro: ocoreu um erro ao tentarmos remover o paciente no banco de dados, tente novamente mais tarde",
    BANCO_DE_DADOS_ERRRO_CONSULTA_LISTA: "Erro: ocorreu um erro ao tentarmos listar todos os pacientes no banco de dados, tente novamente mais tarde"
}